name: Market-intelligence
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3 
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - matplotlib
  - python-dotenv 
  - requests==2.27.1 
  - pip
  - pip:
    - -e .  # make the project editable package, conda >= 4.4 only
    - --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org # to avoid problems with proxies
    - tweepy
    - wordcloud 

    
  
